---
apiVersion: v1
kind: Service
metadata:
  name: [CASSANDRA_NAME]
  labels:
    name: [CASSANDRA_NAME]
    service: [CASSANDRA_NAME]
spec:
  ports:
    - port: 9042
      name: cql
  selector:
    service: [CASSANDRA_NAME]

