apiVersion: v1
kind: Service
metadata:
  name: [ENV_NAME]-discovery
  labels:
    component: [ENV_NAME]
    role: master
spec:
  selector:
    component: [ENV_NAME]
    role: master
  ports:
  - name: transport
    port: 9300
    protocol: TCP
