apiVersion: v1
kind: Service
metadata:
  name: [ENV_NAME]
  labels:
    component: [ENV_NAME]
    role: client
spec:
  selector:
    component: [ENV_NAME]
    role: client
  ports:
  - name: http
    port: 9200
    protocol: TCP

